name: pytest

on:
  push:
    branches:
      - test
  pull_request: {}
  workflow_dispatch: {}

jobs:
  pytest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --progress-bar off -U pip setuptools wheel
          python -m pip install --no-cache-dir --progress-bar off -U .[tests]
      - name: Check with pytest on flask-server
        run: |
          which docker
          ls /var/run
          env
          TEST_SERVER_MODE=flask pytest -s ./tests/unit_test/test_post_runs/cwltool/test_remote_workflow.py
      - name: Check with pytest on uwsgi-server
        run: |
          TEST_SERVER_MODE=uwsgi pytest -s ./tests/unit_test/test_post_runs/cwltool/test_remote_workflow.py
